---
- name: Nginx Install - Debian Platform
  apt: name=nginx state=latest
  when: ansible_os_family == 'Debian'
  notify:
    name: Start Nginx

- name: Nginx Install - RHEL Platform
  yum: pkg=nginx state=latest
  when: ansible_os_family == "RedHat"
  notify:
     name: Start Nginx

